# Class 7

## Task 1

The following code iterates over a list of words and assigns a fifth letter of each word to the new list `fifth_letter`. The current version of the code produces an exception. <b>Your task is to include a try/except clause that will allow the code to run and produce a list of the fifth letter in each word, only for the words that are long enough.</b>

In [ ]:
words = ["chocolate", "chicken", "soup", "potatoes", "beef", "lox", "beef"]
fifth_letter = []

for w in words:
  try:
    fifth_letter.append(w[4])
  except:
    pass

print(fifth_letter)

['o', 'k', 't']


## Task 2

The following function is suppose to safely return the element specified by the index from a list of values – i.e., if the index is outside the bounds of the list, it should return the constant `None`. At the moment, it generates an error. Include a try/except clause to handle the error.

In [3]:
def get_value(values, index):
  try:
    return values[index]
  except:
    return None

# sample list data
my_list = ['a', 'b', 'c']

print(get_value(my_list, 1))
print(get_value(my_list, 4))

b
None


## Task 3

Write a function called `batch_log` that calculates and prints the log base 10 value for each element of a list passed as parameter. Use exception handling to skip the calculation of any value that produces an error.

In [58]:
# import math library (required for log function)
import math

# write your function here – use math.log() to calculate the log value
def batch_log(values):
  for value in values:
    try:
      res = math.log10(value)
      print(f"Log base 10 of {value} is: {res}")
    except:
      pass
      # print(f"Cannot calculate log base 10 of {value}. Skipping...")

values = [0.8, -0.1, 0.9, -0.1, 0.1, 0.300000000004, -0.1, 0.5, 1.0, -0.1, 0.9, 0.9, 0.1, 1.0, 0.2, 0.2, 0.1, 0.9, 0.0, 1.0]

batch_log(values)

Log base 10 of 0.8 is: -0.09691001300805639
Log base 10 of 0.9 is: -0.045757490560675115
Log base 10 of 0.1 is: -1.0
Log base 10 of 0.300000000004 is: -0.5228787452745469
Log base 10 of 0.5 is: -0.3010299956639812
Log base 10 of 1.0 is: 0.0
Log base 10 of 0.9 is: -0.045757490560675115
Log base 10 of 0.9 is: -0.045757490560675115
Log base 10 of 0.1 is: -1.0
Log base 10 of 1.0 is: 0.0
Log base 10 of 0.2 is: -0.6989700043360187
Log base 10 of 0.2 is: -0.6989700043360187
Log base 10 of 0.1 is: -1.0
Log base 10 of 0.9 is: -0.045757490560675115
Log base 10 of 1.0 is: 0.0


## Task 4

Consider the following implementation of an `Account` class and a `withdraw` method. create a custom exception type name `InsufficientBalanceError` and modify the code to raise this type of exception every time there is an attempt to withdraw a value greater than the current available balance:

In [59]:
class InsufficientBalanceError(Exception):
  def __init__(self, message):
    super().__init__(message)

class Account:
  def __init__(self, number, balance):
    self.number = number
    self.balance = balance
  def withdraw(self, value):
    # TODO: withdraw cannot happen if value is greater than balance
    if value > self.balance:
      raise InsufficientBalanceError("Insufficient balance to withdraw")
    self.balance -= value

# sample code
account = Account("1000", 100)

try:
  account.withdraw(200)
except InsufficientBalanceError as e:
  print(e)

Insufficient balance to withdraw


## library for Task 5 - 8

In [8]:
import numpy as np

## Task 5

Create a NumPy multidimensional array (10 rows x 5 columns) with random values.

In [60]:
# generate a 10x5 array with random values int values
array = np.random.randint(10, size=(10, 5))

array = np.random.rand(10, 5)

print(array)

[[0.60052519 0.14442252 0.94734734 0.77920952 0.22674332]
 [0.33610294 0.44023658 0.86149095 0.59479741 0.28560383]
 [0.87873755 0.20284501 0.41562697 0.6144704  0.93558556]
 [0.00163949 0.15182416 0.56389649 0.05762617 0.0755388 ]
 [0.87535576 0.9755122  0.63478875 0.78106795 0.44946496]
 [0.34422215 0.04223557 0.33087583 0.13030623 0.26711926]
 [0.4644088  0.10762117 0.33641731 0.4317261  0.42219363]
 [0.12097149 0.67523074 0.62735267 0.48180813 0.90286642]
 [0.65719188 0.3972327  0.9479071  0.71507015 0.49274441]
 [0.56547824 0.59615617 0.00815955 0.90950799 0.96278616]]


## Task 6

In [46]:
def hightest_mean_row_index():
  """
    Using the array created in (5), write a function that returns the index of the row with the highest mean value.
  """
  # calculate the mean value for each row
  mean_values = np.mean(array, axis=1)

  # find the index of the row with the highest mean value
  highest_mean_index = np.argmax(mean_values)

  return highest_mean_index

hightest_mean_row_index()

8

## Task 7

In [47]:
def hightest_mean_col_index():
  """
    Using the array created in (5), write a function that returns the index of the column with the highest mean value.
  """
  # calculate the mean value for each column
  mean_values = np.mean(array, axis=0)

  # find the index of the column with the highest mean value
  highest_mean_index = np.argmax(mean_values)

  return highest_mean_index

hightest_mean_col_index()

2

## Task 8

In [ ]:
def max_in_row_n_col():
  """
    Using the array create in (5), write a function that return a tuple (row, column) representing the indexes of the row and column of the maximum value in the array.
  """

  print(np.argmax(array))
  # Get the index of the max value in each row and column
  max_value_indices = np.unravel_index(np.argmax(array), array.shape)

  return max_value_indices

max_in_row_n_col()

7


(1, 2)