# Class 7

## Task 1

The following code iterates over a list of words and assigns a fifth letter of each word to the new list `fifth_letter`. The current version of the code produces an exception. <b>Your task is to include a try/except clause that will allow the code to run and produce a list of the fifth letter in each word, only for the words that are long enough.</b>

In [1]:
words = ["chocolate", "chicken", "soup", "potatoes", "beef", "lox", "beef"]
fifth_letter = []

for w in words:
  try:
    fifth_letter.append(w[4])
  except:
    pass

print(fifth_letter)

['o', 'k', 't']


## Task 2

The following function is suppose to safely return the element specified by the index from a list of values – i.e., if the index is outside the bounds of the list, it should return the constant `None`. At the moment, it generates an error. Include a try/except clause to handle the error.

In [2]:
def get_value(values, index):
  try:
    return values[index]
  except:
    return None

# sample list data
my_list = ['a', 'b', 'c']

print(get_value(my_list, 1))
print(get_value(my_list, 4))

b
None


## Task 3

Write a function called `batch_log` that calculates and prints the log base 10 value for each element of a list passed as parameter. Use exception handling to skip the calculation of any value that produces an error.

In [3]:
# import math library (required for log function)
import math

# write your function here – use math.log() to calculate the log value
def batch_log(values):
  for value in values:
    try:
      res = math.log10(value)
      print(f"Log base 10 of {value} is: {res}")
    except:
      pass
      # print(f"Cannot calculate log base 10 of {value}. Skipping...")

values = [0.8, -0.1, 0.9, -0.1, 0.1, 0.300000000004, -0.1, 0.5, 1.0, -0.1, 0.9, 0.9, 0.1, 1.0, 0.2, 0.2, 0.1, 0.9, 0.0, 1.0]

batch_log(values)

Log base 10 of 0.8 is: -0.09691001300805639
Log base 10 of 0.9 is: -0.045757490560675115
Log base 10 of 0.1 is: -1.0
Log base 10 of 0.300000000004 is: -0.5228787452745469
Log base 10 of 0.5 is: -0.3010299956639812
Log base 10 of 1.0 is: 0.0
Log base 10 of 0.9 is: -0.045757490560675115
Log base 10 of 0.9 is: -0.045757490560675115
Log base 10 of 0.1 is: -1.0
Log base 10 of 1.0 is: 0.0
Log base 10 of 0.2 is: -0.6989700043360187
Log base 10 of 0.2 is: -0.6989700043360187
Log base 10 of 0.1 is: -1.0
Log base 10 of 0.9 is: -0.045757490560675115
Log base 10 of 1.0 is: 0.0


## Task 4

Consider the following implementation of an `Account` class and a `withdraw` method. create a custom exception type name `InsufficientBalanceError` and modify the code to raise this type of exception every time there is an attempt to withdraw a value greater than the current available balance:

In [4]:
class InsufficientBalanceError(Exception):
  def __init__(self, message):
    super().__init__(message)

class Account:
  def __init__(self, number, balance):
    self.number = number
    self.balance = balance
  def withdraw(self, value):
    # TODO: withdraw cannot happen if value is greater than balance
    if value > self.balance:
      raise InsufficientBalanceError("Insufficient balance to withdraw")
    self.balance -= value

# sample code
account = Account("1000", 100)

try:
  account.withdraw(200)
except InsufficientBalanceError as e:
  print(e)

Insufficient balance to withdraw


## library for Task 5 - 8

In [5]:
import numpy as np

## Task 5

Create a NumPy multidimensional array (10 rows x 5 columns) with random values.

In [6]:
# generate a 10x5 array with random values int values
# array = np.random.randint(10, size=(10, 5))

array = np.random.rand(10, 5)

print(array)

[[0.25364866 0.17956654 0.98590084 0.77123217 0.81976561]
 [0.17905503 0.35446245 0.04218414 0.07250329 0.28900973]
 [0.71991256 0.12261652 0.48701662 0.2974309  0.53178764]
 [0.00846887 0.3456749  0.47983066 0.73178103 0.88604267]
 [0.40484168 0.06274275 0.45883561 0.4458476  0.63908785]
 [0.87675039 0.84946657 0.56690883 0.99422233 0.89035527]
 [0.81019191 0.00643485 0.49118783 0.3158558  0.40278201]
 [0.3754571  0.23551282 0.67772824 0.67499856 0.32433672]
 [0.66183463 0.33396304 0.67509483 0.58373473 0.84926929]
 [0.16221031 0.69521632 0.68886204 0.94511166 0.59139792]]


## Task 6

In [7]:
def hightest_mean_row_index():
  """
    Using the array created in (5), write a function that returns the index of the row with the highest mean value.
  """
  # calculate the mean value for each row
  mean_values = np.mean(array, axis=1)

  # find the index of the row with the highest mean value
  highest_mean_index = np.argmax(mean_values)

  return highest_mean_index

hightest_mean_row_index()

5

## Task 7

In [8]:
def hightest_mean_col_index():
  """
    Using the array created in (5), write a function that returns the index of the column with the highest mean value.
  """
  # calculate the mean value for each column
  mean_values = np.mean(array, axis=0)

  # find the index of the column with the highest mean value
  highest_mean_index = np.argmax(mean_values)

  return highest_mean_index

hightest_mean_col_index()

4

## Task 8

In [9]:
def max_in_row_n_col():
  """
    Using the array create in (5), write a function that return a tuple (row, column) representing the indexes of the row and column of the maximum value in the array.
  """

  # find the index of all in the array with the highest value, flat_indices
  highest_index = np.argmax(array)
    
  # Get the index of the max value in each row and column
  max_value_indices = np.unravel_index(highest_index, array.shape)

  return max_value_indices

max_in_row_n_col()

(5, 3)